### ISSUE TITLE
Rename repo to StreamRadio

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/StreamRadio#13]

**Comment by Vidrep** [comment]
This is the only remaining open issue for this app. Can we rename?

**Comment by waddlesplash** [comment]
Done. Should I also ask GitHub to "de-fork" this repository?

**Comment by humdingerb** [comment]
I'm not exactly sure what that entails... it invalidates existing forks, so people have to re-fork?
Left to your disgression...

**Comment by Begasus** [comment]
Think this one can be closed too?
