### ISSUE TITLE
Add help menu item

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/StreamRadio#16]
Add a help menu item with links to usage instructions and the project website

**Comment by Begasus** [comment]
A help item in the menu pointing to the doc recently merged here would be enough I think (https://github.com/HaikuArchives/Haiku-Radio/blob/master/docs/userguide.md)

**Comment by jsteinaker** [comment]
Done on jsteinaker/HaikuRadio/b838739acffccbe1346524d7caaa3e1d3abda8fa
(I'll merge the features branch to my master if everything's working)

Side note: I've tried to make the F1 key to open the help, with no success. I've seen B_F1_KEY on the documentation, tried to use it. Code compiled but nothing happened when I pressed the key, with or without modificators. Is there any reason for this? Is F1 the key commonly used for help in Haiku?

In the end, I just used Command + H, but I'm all ears.

**Comment by humdingerb** [comment]
The F1 key isn't used as a 'help' key in Haiku. Good thing, with Windows at work I keep hitting F1 accidentally and have to wait a felt eternity for the doc viewer to pop up so I can close it again...

Shortcuts should only be used for commands that are used regularly. So, I'd just add a 'Help' item with no shortcut.

WRT your help-branch: I propose renaming 'File' to 'App' and put Help, About, Separator, Quit items there.

**Comment by jsteinaker** [comment]
I followed your advice, it makes a lot of sense. I've updated the pull request with this already in place.

**Comment by pulkomandy** [comment]
The F keys are a bit special, you have to check for the key string to be B_FUNCTION_KEY and then check the keycode to be B_F1_KEY.
This is documented in the Be Book: https://www.haiku-os.org/legacy-docs/bebook/TheKeyboard_CharacterConstants.html

**Comment by Vidrep** [comment]
Can we close this now?

**Comment by humdingerb** [comment]
Yes, we can! :)
