### ISSUE TITLE
Use a BSplitView instead of the custom "Expander" view at the bottom

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/StreamRadio#22]
Always nicer to use what the Haiku API provides. The split can jump from hide to show, like the FileTypes preferences.

**Comment by CodeforEvolution** [comment]
That's true, though I honestly feel that BSplitViews could be improved (they're very hard to see and don't communicate well how a user should interact with them in my opinion). I'll add this for now, just for future proofing per se.
