### ISSUE TITLE
Double mouse click launch causes crash

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/StreamRadio#29]
`Debug information for team /boot/home/haikuarchives/StreamRadio/dist/StreamRadio (4048):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 837.00 MiB used
Haiku revision: hrev54526 Aug 22 2020 06:44:23 (x86_64)

Active Threads:
	thread 4051: team 4048 debug task 
	thread 4048: StreamRadio (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7fc0b98c3840	0x175f37a348	scale_bilinear(unsigned char*, int, int, int, int, unsigned int) + 0x1d8 
			Disassembly:
				scale_bilinear(unsigned char*, int, int, int, int, unsigned int):
				0x000000175f37a170:               55  push %rbp
				0x000000175f37a171:         4183e801  sub $0x1, %r8d
				0x000000175f37a175:           4489c0  mov %r8d, %eax
				0x000000175f37a178:         410fafc1  imul %r9d, %eax
				0x000000175f37a17c:           4889e5  mov %rsp, %rbp
				0x000000175f37a17f:             4157  push %r15
				0x000000175f37a181:             4156  push %r14
				0x000000175f37a183:             4155  push %r13
				0x000000175f37a185:           4801f8  add %rdi, %rax
				0x000000175f37a188:             4154  push %r12
				0x000000175f37a18a:               53  push %rbx
				0x000000175f37a18b:           8975c8  mov %esi, -0x38(%rbp)
				0x000000175f37a18e:           894dcc  mov %ecx, -0x34(%rbp)
				0x000000175f37a191:         488945c0  mov %rax, -0x40(%rbp)
				0x000000175f37a195:             85f6  test %esi, %esi
				0x000000175f37a197:     0f8e18010000  jle 0x175f37a2b5
				0x000000175f37a19d:           8b45c8  mov -0x38(%rbp), %eax
				0x000000175f37a1a0:           4531f6  xor %r14d, %r14d
				0x000000175f37a1a3:         448d62ff  lea -0x1(%rdx), %r12d
				0x000000175f37a1a7:           83e801  sub $0x1, %eax
				0x000000175f37a1aa: 488d048504000000  lea 0x4(%rax,4), %rax
				0x000000175f37a1b2:         488945b8  mov %rax, -0x48(%rbp)
				0x000000175f37a1b6:           4489c8  mov %r9d, %eax
				0x000000175f37a1b9:         488945d0  mov %rax, -0x30(%rbp)
				0x000000175f37a1bd:           4989c5  mov %rax, %r13
				0x000000175f37a1c0:           49f7dd  neg %r13
				0x000000175f37a1c3:       0f1f440000  nop (%rax,%rax)
				0x000000175f37a1c8:         488b45c0  mov -0x40(%rbp), %rax
				0x000000175f37a1cc:           4963de  movsxd %r14d, %rbx
				0x000000175f37a1cf:           4589c3  mov %r8d, %r11d
				0x000000175f37a1d2:         4a8d3430  lea (%rax,%r14), %rsi
				0x000000175f37a1d6:           4585c0  test %r8d, %r8d
				0x000000175f37a1d9:             792e  jns 0x5f37a209
				0x000000175f37a1db:       e9c7000000  jmp 0x175f37a2a7
				0x000000175f37a1e0:           448816  mov %r10b, (%rsi)
				0x000000175f37a1e3:         0fb64101  movzx 0x1(%rcx), %eax
				0x000000175f37a1e7:         4183eb01  sub $0x1, %r11d
				0x000000175f37a1eb:           884601  mov %al, 0x1(%rsi)
				0x000000175f37a1ee:         0fb64102  movzx 0x2(%rcx), %eax
				0x000000175f37a1f2:           884602  mov %al, 0x2(%rsi)
				0x000000175f37a1f5:         0fb64103  movzx 0x3(%rcx), %eax
				0x000000175f37a1f9:           884603  mov %al, 0x3(%rsi)
				0x000000175f37a1fc:           4c01ee  add %r13, %rsi
				0x000000175f37a1ff:         4183fbff  cmp $0xffffffff, %r11d
				0x000000175f37a203:     0f849e000000  jz 0x175f37a2a7
				0x000000175f37a209:           4489d8  mov %r11d, %eax
				0x000000175f37a20c:           c1e008  shl $0x8, %eax
				0x000000175f37a20f:         410fafc4  imul %r12d, %eax
				0x000000175f37a213:               99  cdq 
				0x000000175f37a214:           41f7f8  idiv %r8d
				0x000000175f37a217:             89c1  mov %eax, %ecx
				0x000000175f37a219:           c1f908  sar $0x8, %ecx
				0x000000175f37a21c:         410fafc9  imul %r9d, %ecx
				0x000000175f37a220:           4801d9  add %rbx, %rcx
				0x000000175f37a223:           4801f9  add %rdi, %rcx
				0x000000175f37a226:         440fb611  movzx (%rcx), %r10d
				0x000000175f37a22a:             84c0  test %al, %al
				0x000000175f37a22c:             74b2  jz 0x5f37a1e0
				0x000000175f37a22e:         488b55d0  mov -0x30(%rbp), %rdx
				0x000000175f37a232:           0fb6c0  movzx %al, %eax
				0x000000175f37a235:         4183eb01  sub $0x1, %r11d
				0x000000175f37a239:         4c8d3c11  lea (%rcx,%rdx), %r15
				0x000000175f37a23d:         410fb617  movzx (%r15), %edx
				0x000000175f37a241:           4429d2  sub %r10d, %edx
				0x000000175f37a244:         41c1e208  shl $0x8, %r10d
				0x000000175f37a248:           0fafd0  imul %eax, %edx
				0x000000175f37a24b:           4401d2  add %r10d, %edx
				0x000000175f37a24e:             8836  mov %dh, (%rsi)
				0x000000175f37a250:       440fb65101  movzx 0x1(%rcx), %r10d
				0x000000175f37a255:       410fb65701  movzx 0x1(%r15), %edx
				0x000000175f37a25a:           4429d2  sub %r10d, %edx
				0x000000175f37a25d:         41c1e208  shl $0x8, %r10d
				0x000000175f37a261:           0fafd0  imul %eax, %edx
				0x000000175f37a264:           4401d2  add %r10d, %edx
				0x000000175f37a267:           887601  mov %dh, 0x1(%rsi)
				0x000000175f37a26a:       440fb65102  movzx 0x2(%rcx), %r10d
				0x000000175f37a26f:       410fb65702  movzx 0x2(%r15), %edx
				0x000000175f37a274:           4429d2  sub %r10d, %edx
				0x000000175f37a277:         41c1e208  shl $0x8, %r10d
				0x000000175f37a27b:           0fafd0  imul %eax, %edx
				0x000000175f37a27e:           4401d2  add %r10d, %edx
				0x000000175f37a281:           887602  mov %dh, 0x2(%rsi)
				0x000000175f37a284:         0fb64903  movzx 0x3(%rcx), %ecx
				0x000000175f37a288:       410fb65703  movzx 0x3(%r15), %edx
				0x000000175f37a28d:             29ca  sub %ecx, %edx
				0x000000175f37a28f:           c1e108  shl $0x8, %ecx
				0x000000175f37a292:           0fafc2  imul %edx, %eax
				0x000000175f37a295:             01c8  add %ecx, %eax
				0x000000175f37a297:           886603  mov %ah, 0x3(%rsi)
				0x000000175f37a29a:           4c01ee  add %r13, %rsi
				0x000000175f37a29d:         4183fbff  cmp $0xffffffff, %r11d
				0x000000175f37a2a1:     0f8562ffffff  jnz 0x175f37a209
				0x000000175f37a2a7:         4983c604  add $0x4, %r14
				0x000000175f37a2ab:         4c3975b8  cmp %r14, -0x48(%rbp)
				0x000000175f37a2af:     0f8513ffffff  jnz 0x175f37a1c8
				0x000000175f37a2b5:           8b45cc  mov -0x34(%rbp), %eax
				0x000000175f37a2b8:         448d50ff  lea -0x1(%rax), %r10d
				0x000000175f37a2bc: 468d249500000000  lea (%r10,4), %r12d
				0x000000175f37a2c4:           4d63e4  movsxd %r12d, %r12
				0x000000175f37a2c7:           4901fc  add %rdi, %r12
				0x000000175f37a2ca:             85c0  test %eax, %eax
				0x000000175f37a2cc:     0f8e07010000  jle 0x175f37a3d9
				0x000000175f37a2d2:           4489c8  mov %r9d, %eax
				0x000000175f37a2d5:           8b5dc8  mov -0x38(%rbp), %ebx
				0x000000175f37a2d8:           4531f6  xor %r14d, %r14d
				0x000000175f37a2db:           4531ed  xor %r13d, %r13d
				0x000000175f37a2de:         488945d0  mov %rax, -0x30(%rbp)
				0x000000175f37a2e2:           83eb01  sub $0x1, %ebx
				0x000000175f37a2e5:           0f1f00  nop (%rax)
				0x000000175f37a2e8:           4589f3  mov %r14d, %r11d
				0x000000175f37a2eb:           4589d0  mov %r10d, %r8d
				0x000000175f37a2ee:           4c89e6  mov %r12, %rsi
				0x000000175f37a2f1:           4585d2  test %r10d, %r10d
				0x000000175f37a2f4:             7934  jns 0x5f37a32a
				0x000000175f37a2f6:       e9c9000000  jmp 0x175f37a3c4
				0x000000175f37a2fb:       0f1f440000  nop (%rax,%rax)
				0x000000175f37a300:           44883e  mov %r15b, (%rsi)
				0x000000175f37a303:         0fb64101  movzx 0x1(%rcx), %eax
				0x000000175f37a307:         4183e801  sub $0x1, %r8d
				0x000000175f37a30b:         4883ee04  sub $0x4, %rsi
				0x000000175f37a30f:           884605  mov %al, 0x5(%rsi)
				0x000000175f37a312:         0fb64102  movzx 0x2(%rcx), %eax
				0x000000175f37a316:           884606  mov %al, 0x6(%rsi)
				0x000000175f37a319:         0fb64103  movzx 0x3(%rcx), %eax
				0x000000175f37a31d:           884607  mov %al, 0x7(%rsi)
				0x000000175f37a320:         4183f8ff  cmp $0xffffffff, %r8d
				0x000000175f37a324:     0f849a000000  jz 0x175f37a3c4
				0x000000175f37a32a:           4489c0  mov %r8d, %eax
				0x000000175f37a32d:           c1e008  shl $0x8, %eax
				0x000000175f37a330:           0fafc3  imul %ebx, %eax
				0x000000175f37a333:               99  cdq 
				0x000000175f37a334:           41f7fa  idiv %r10d
				0x000000175f37a337:             89c1  mov %eax, %ecx
				0x000000175f37a339:           c1f908  sar $0x8, %ecx
				0x000000175f37a33c:           c1e102  shl $0x2, %ecx
				0x000000175f37a33f:           4863c9  movsxd %ecx, %rcx
				0x000000175f37a342:           4c01d9  add %r11, %rcx
				0x000000175f37a345:           4801f9  add %rdi, %rcx
				0x000000175f37a348:         440fb639  movzx (%rcx), %r15d <--

			Frame memory:
				[0x7fc0b98c3808]  P....... .......   50 ed eb 88 b3 11 00 00 20 00 00 00 00 00 00 00
				[0x7fc0b98c3818]   ...............   20 00 00 00 00 00 00 00 c0 ed eb 88 b3 11 00 00
				[0x7fc0b98c3828]  ...h.....8......   e0 f0 01 68 00 00 00 00 c0 38 8c b9 c0 7f 00 00
				[0x7fc0b98c3838]  ..7_....           f1 b7 37 5f 17 00 00 00
		0x7fc0b98c38d0	0x175f37b7ec	BIconUtils::ConvertFromCMAP8(unsigned char const*, unsigned int, unsigned int, unsigned int, BBitmap*) + 0x78c 
		0x7fc0b98c3960	0x175f37bb4d	BIconUtils::GetCMAP8Icon(BNode*, char const*, char const*, icon_size, BBitmap*) + 0x30d 
		0x7fc0b98c3a30	0x175f37c907	BIconUtils::GetIcon(BNode*, char const*, char const*, char const*, icon_size, BBitmap*) + 0x217 
		0x7fc0b98c3bd0	0x196377f3953	Station::Load(BString, BEntry*) + 0x373 
		0x7fc0b98c3c50	0x196377f41d8	Station::LoadFromPlsFile(BString) + 0x58 
		0x7fc0b98c3cf0	0x196377f16c3	StationsList::Load() + 0x43 
		0x7fc0b98c3e40	0x196377f19da	RadioSettings::_Load() + 0xca 
		0x7fc0b98c3e70	0x196377f1a3f	RadioSettings::RadioSettings() + 0x3f 
		0x7fc0b98c3e90	0x196377f0fbb	RadioApp::RadioApp() + 0x2b 
		0x7fc0b98c3eb0	0x196377edcec	main + 0x1c 
		0x7fc0b98c3ee0	0x196377ee089	_start + 0x39 
		0x7fc0b98c3f10	0x1b17d0b8483	runtime_loader + 0x103 
		00000000	0x7ff8ba045260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000000175f37a348
			  rsp:	0x00007fc0b98c3808
			  rbp:	0x00007fc0b98c3830
			  rax:	0x0000000000001f00
			  rbx:	0x000000000000001f
			  rcx:	0x00000000681c504c
			  rdx:	0x0000000000000000
			  rsi:	0x00000000681c5468
			  rdi:	0x0000000068181000
			   r8:	0x0000000000000126
			   r9:	0x000000000000049c
			  r10:	0x0000000000000126
			  r11:	0x0000000000043fd0
			  r12:	0x00000000681c5468
			  r13:	0x00000000000000ec
			  r14:	0x0000000000043fd0
			  r15:	0x0000000000000000
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff}
			 xmm1:	{0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff}
			 xmm2:	{0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff}
			 xmm3:	{0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff, 0xff00, 0xffff}
			 xmm4:	{0, 0x3f80, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0x3f80, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0x4b00, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0x4b00, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	8150	0x167423e000	0x167425a000	0x1674459000	0x167445a000	lib    	/boot/system/lib/libz.so.1.2.11
	8139	0x175f0f5000	0x175f40d000	0x175f60c000	0x175f63a000	lib    	/boot/system/lib/libbe.so
	8140	0x2cab3f1000	0x2cab406000	0x2cab605000	0x2cab607000	lib    	/boot/system/lib/libtranslation.so
	8154	0x596e595000	0x596e7a3000	0x596e9a3000	0x596e9d2000	lib    	/boot/system/lib/libcrypto.so.1.1
	8145	0x5a19917000	0x5a1b197000	0x5a1b396000	0x5a1b397000	lib    	/boot/system/lib/libicudata.so.57.2
	8147	0x63b47a5000	0x63b47b1000	0x63b49b0000	0x63b49b2000	lib    	/boot/system/lib/libicuio.so.57.2
	8141	0x66142f9000	0x661435f000	0x661455e000	0x6614563000	lib    	/boot/system/lib/libbnetapi.so
	8152	0xbd3292d000	0xbd32a28000	0xbd32c27000	0xbd32c2a000	lib    	/boot/system/lib/libtextencoding.so
	8151	0xdea7f13000	0xdea7fdf000	0xdea81de000	0xdea81df000	lib    	/boot/system/lib/libzstd.so.1.4.5
	8142	0x10ba8062000	0x10ba8115000	0x10ba8315000	0x10ba8321000	lib    	/boot/system/lib/libmedia.so
	8146	0x130dcf27000	0x130dd1a3000	0x130dd3a3000	0x130dd3b8000	lib    	/boot/system/lib/libicui18n.so.57.2
	8143	0x1362c945000	0x1362c95b000	0x1362cb5a000	0x1362cb5b000	lib    	/boot/system/lib/libgcc_s.so.1
	8156	0x14f898ec000	0x14f898f3000	0x14f89af2000	0x14f89af3000	lib    	/boot/system/lib/libbsd.so
	8155	0x16e42b52000	0x16e42bd6000	0x16e42dd6000	0x16e42de3000	lib    	/boot/system/lib/libssl.so.1.1
	8153	0x180aeb21000	0x180aeb61000	0x180aed60000	0x180aed69000	lib    	/boot/system/lib/libnetwork.so
	8149	0x18df1373000	0x18df1507000	0x18df1707000	0x18df171c000	lib    	/boot/system/lib/libicuuc.so.57.2
	8137	0x196377ce000	0x19637805000	0x19637a05000	0x19637a09000	app    	/boot/home/haikuarchives/StreamRadio/dist/StreamRadio
	8136	0x1b17d0a4000	0x1b17d0c5000	0x1b17d2c4000	0x1b17d2c6000	lib    	/boot/system/runtime_loader
	8148	0x1da3a330000	0x1da3a35e000	0x1da3a55e000	0x1da3a592000	lib    	/boot/system/lib/libicutu.so.57.2
	8144	0x1da4fdd2000	0x1da4fedf000	0x1da500df000	0x1da50131000	lib    	/boot/system/lib/libroot.so
	8138	0x240bf1f0000	0x240bf352000	0x240bf552000	0x240bf566000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	8135	0x7ff8ba045000	0x7ff8ba04d000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	32228	0x60000000	0x60001000	         4	rw-S, u:(0x100)	full          	server_memory
	32230	0x68000000	0x681c5000	      1812	rw-S, u:(0x100)	full          	server_memory
	32200	0x167423e000	0x167425a000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	32201	0x1674459000	0x167445a000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	32176	0x175f0f5000	0x175f40d000	      3168	r-x        	full          	libbe.so_seg0ro
	32177	0x175f60c000	0x175f63a000	       184	rw-        	full          	libbe.so_seg1rw
	32169	0x2014cc8000	0x2014cd8000	        64	rw-        	full          	rld heap
	32178	0x2cab3f1000	0x2cab406000	        84	r-x        	full          	libtranslation.so_seg0ro
	32179	0x2cab605000	0x2cab607000	         8	rw-        	full          	libtranslation.so_seg1rw
	32209	0x596e595000	0x596e7a3000	      2104	r-x        	full          	libcrypto.so.1.1_seg0ro
	32210	0x596e9a3000	0x596e9cf000	       176	rw-        	full          	libcrypto.so.1.1_seg1rw
	32211	0x596e9cf000	0x596e9d2000	        12	rw-        	full          	libcrypto.so.1.1_seg2rw
	32189	0x5a19917000	0x5a1b197000	     25088	r-x        	full          	libicudata.so.57.2_seg0ro
	32190	0x5a1b396000	0x5a1b397000	         4	rw-        	full          	libicudata.so.57.2_seg1rw
	32193	0x63b47a5000	0x63b47b1000	        48	r-x        	full          	libicuio.so.57.2_seg0ro
	32194	0x63b49b0000	0x63b49b2000	         8	rw-        	full          	libicuio.so.57.2_seg1rw
	32180	0x66142f9000	0x661435f000	       408	r-x        	full          	libbnetapi.so_seg0ro
	32181	0x661455e000	0x6614563000	        20	rw-        	full          	libbnetapi.so_seg1rw
	32170	0x681636d000	0x681636e000	         4	rw-S, u:(0x100)	full          	_rld_debug_
	32216	0xb4c69ae000	0xb4c69b6000	        32	rw-        	full          	rld heap
	32217	0xbb09bbf000	0xbb09bcf000	        64	rw-        	full          	rld heap
	32218	0xbb1b063000	0xbb1b073000	        64	rw-        	full          	rld heap
	32219	0xbc16813000	0xbc1682b000	        96	rw-        	full          	rld heap
	32220	0xbd2c7a1000	0xbd2c7b9000	        96	rw-        	full          	rld heap
	32204	0xbd3292d000	0xbd32a28000	      1004	r-x        	full          	libtextencoding.so_seg0ro
	32205	0xbd32c27000	0xbd32c2a000	        12	rw-        	full          	libtextencoding.so_seg1rw
	32202	0xdea7f13000	0xdea7fdf000	       816	r-x        	full          	libzstd.so.1.4.5_seg0ro
	32203	0xdea81de000	0xdea81df000	         4	rw-        	full          	libzstd.so.1.4.5_seg1rw
	32182	0x10ba8062000	0x10ba8115000	       716	r-x        	full          	libmedia.so_seg0ro
	32183	0x10ba8315000	0x10ba8321000	        48	rw-        	full          	libmedia.so_seg1rw
	32191	0x130dcf27000	0x130dd1a3000	      2544	r-x        	full          	libicui18n.so.57.2_seg0ro
	32192	0x130dd3a3000	0x130dd3b8000	        84	rw-        	full          	libicui18n.so.57.2_seg1rw
	32184	0x1362c945000	0x1362c95b000	        88	r-x        	full          	libgcc_s.so.1_seg0ro
	32185	0x1362cb5a000	0x1362cb5b000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	32214	0x14f898ec000	0x14f898f3000	        28	r-x        	full          	libbsd.so_seg0ro
	32215	0x14f89af2000	0x14f89af3000	         4	rw-        	full          	libbsd.so_seg1rw
	32212	0x16e42b52000	0x16e42bd6000	       528	r-x        	full          	libssl.so.1.1_seg0ro
	32213	0x16e42dd6000	0x16e42de3000	        52	rw-        	full          	libssl.so.1.1_seg1rw
	32206	0x180aeb21000	0x180aeb61000	       256	r-x        	full          	libnetwork.so_seg0ro
	32207	0x180aed60000	0x180aed63000	        12	rw-        	full          	libnetwork.so_seg1rw
	32208	0x180aed63000	0x180aed69000	        24	rw-        	full          	libnetwork.so_seg2rw
	32198	0x18df1373000	0x18df1507000	      1616	r-x        	full          	libicuuc.so.57.2_seg0ro
	32199	0x18df1707000	0x18df171c000	        84	rw-        	full          	libicuuc.so.57.2_seg1rw
	32171	0x196377ce000	0x19637805000	       220	r-x        	full          	StreamRadio_seg0ro
	32172	0x19637a05000	0x19637a09000	        16	rw-        	full          	StreamRadio_seg1rw
	32167	0x1b17d0a4000	0x1b17d0c5000	       132	r-x        	full          	runtime_loader_seg0ro
	32168	0x1b17d2c4000	0x1b17d2c6000	         8	rw-        	full          	runtime_loader_seg1rw
	32195	0x1da3a330000	0x1da3a35e000	       184	r-x        	full          	libicutu.so.57.2_seg0ro
	32196	0x1da3a55e000	0x1da3a560000	         8	rw-        	full          	libicutu.so.57.2_seg1rw
	32197	0x1da3a560000	0x1da3a592000	       200	rw-        	full          	libicutu.so.57.2_seg2rw
	32186	0x1da4fdd2000	0x1da4fedf000	      1076	r-x        	full          	libroot.so_seg0ro
	32187	0x1da500df000	0x1da500ed000	        56	rw-        	full          	libroot.so_seg1rw
	32188	0x1da500ed000	0x1da50131000	       272	rw-        	full          	libroot.so_seg2rw
	32173	0x240bf1f0000	0x240bf352000	      1416	r-x        	full          	libstdc++.so.6.0.25_seg0ro
	32174	0x240bf552000	0x240bf55e000	        48	rw-        	full          	libstdc++.so.6.0.25_seg1rw
	32175	0x240bf55e000	0x240bf566000	        32	rw-        	full          	libstdc++.so.6.0.25_seg2rw
	32221	0x11b388e93000	0x11b3891e3000	      3392	rw-, u:(0x100)	full          	heap
	32165	0x7fc0b88c4000	0x7fc0b98c5000	     16388	rw-s       	full          	StreamRadio_4048_stack
	32166	0x7ff8ba045000	0x7ff8ba04d000	        32	r-xSk      	full          	commpage
	32163	0x7ffa95582000	0x7ffa95586000	        16	rw-k       	full          	user area

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	111846	    0	          0	some BBlockCache lock
	111847	    0	          0	token space
	111848	    0	          0	BLooperList lock
	111849	    0	          0	AppServerLink_sLock
	111850	    0	          0	some BLocker
	111851	    0	          0	some BLocker
	111852	    0	          0	Catalog
	111853	    0	          0	LocaleRosterData
	111854	    0	          0	some BLocker
	111855	    0	          0	Catalog
	111856	    0	          0	DNS cache
	111857	    0	          0	synchronized hash map
	111858	    0	          0	synchronized hash map
	111859	    0	          0	some BLocker
	111860	    0	          0	some BLocker
	111861	    0	          0	BMediaRoster::Roster locker
	111862	    0	          0	port pool
	111863	    0	          0	media theme lock
	111864	    0	          0	add-on manager
	111865	    0	          0	shared buffer list
	111866	    0	          0	media plugin manager
	111867	    0	          0	BMessageQueue Lock
	111868	    0	          0	AppLooperPort
	111880	    0	          0	screen list
	111881	    0	          0	clipboard
	111882	    0	          0	width buffer
``

**Comment by humdingerb** [comment]
Is this the same as #32?

**Comment by korli** [comment]
Closing as fixed
