### ISSUE TITLE
Haiku R1 Beta3, Missing symbol: _ZN11BUrlRequest5PauseEv

### ISSUE THREAD

**Issue by smallstepforman** [HaikuArchives/StreamRadio#41]
With hrev55294, SteamRadio will not start, and comes up with BAlert "Could not open "Stream Radio" (Missing symbol: _ZN11BUrlRequest5PauseEv).

**Comment by Vidrep** [comment]
There are two pull requests which address the problem and make the app work again. However, both of the people involved with the fix have gone MIA, and we are left with a memory leak issue which needs to be resolved before merging.

**Comment by pulkomandy** [comment]
Merged the second one. I don't know if it fixes the existing memory leaks, but I pushed fixes so that at least it doesn't introduce new ones, and it should also fix this (temporarily, because it's still using the deprecated version of the API as far as I can see)
