### ISSUE TITLE
Fails to launch - Missing symbol error (_ti20BUrlProtocolListener)

### ISSUE THREAD

**Issue by kenmays** [HaikuArchives/StreamRadio#49]
Tested on hrev56689 x86 w/StreamRadio-1.0.0-1:
Could not open "StreamRadio" (Missing symbol: _ti20BUrlProtocolListener)

**Comment by Brunobasta** [comment]
Same here on Haiku 32bit nightly 56693
http://0x0.st/o7qt.png

**Comment by Brunobasta** [comment]
![radio](https://user-images.githubusercontent.com/67808751/211341334-6591ae25-4337-45a2-acae-2de4c5380585.png)
