### ISSUE TITLE
Clicking On Stations That Are In Deskbar Doesn't Launch The Station

### ISSUE THREAD

**Issue by justingoldberg** [HaikuArchives/StreamRadio#58]
I created a symbolic link to /boot/home/config/settings/station in the deskbar. The stations show on the deskbar but don't launch which click on them. The same behavior occurs if I click on them in the /boot/home/config/settings/station folder itself.

**Comment by humdingerb** [comment]
You'll have to assign the station files filetype to open with StreamRadio, I suppose. The standard is to open "PLS playlist" with MediaPlayer.
Right-click a station file and choose "Open with...".
From the window that pops up, choose StremRadio and click "Open and make preferred".

**Comment by justingoldberg** [comment]
Clicking on them does open StreamRadio, but they don't play.

**Comment by humdingerb** [comment]
I see. Then it really is a bug/enhancement.
